// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelDesk.Data;

#nullable disable

namespace TravelDesk.Migrations
{
    [DbContext(typeof(TravelDeskContext))]
    partial class TravelDeskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravelDesk.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(236),
                            DepartmentName = "IT",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(240),
                            DepartmentName = "HR",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(243),
                            DepartmentName = "Admin",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(246),
                            DepartmentName = "Travel",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("TravelDesk.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(291),
                            IsActive = true,
                            ProjectName = "Project Alpha"
                        },
                        new
                        {
                            ProjectId = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(296),
                            IsActive = true,
                            ProjectName = "Project Beta"
                        },
                        new
                        {
                            ProjectId = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(299),
                            IsActive = true,
                            ProjectName = "Project Gamma"
                        });
                });

            modelBuilder.Entity("TravelDesk.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 496, DateTimeKind.Utc).AddTicks(9753),
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 496, DateTimeKind.Utc).AddTicks(9758),
                            IsActive = true,
                            RoleName = "TravelAdmin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 496, DateTimeKind.Utc).AddTicks(9763),
                            IsActive = true,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 496, DateTimeKind.Utc).AddTicks(9767),
                            IsActive = true,
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("TravelDesk.Models.TravelRequest", b =>
                {
                    b.Property<int>("TravelRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TravelRequestId"));

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonForTravel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TravelRequestId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("TravelRequests");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<string>("MobileNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "123 Admin Street",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(360),
                            DepartmentId = 3,
                            Email = "admin@traveldesk.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            MobileNum = "1234567890",
                            Password = "admin123",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "456 Travel Street",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(368),
                            DepartmentId = 4,
                            Email = "traveladmin@traveldesk.com",
                            FirstName = "Travel",
                            IsActive = true,
                            LastName = "Admin",
                            ManagerId = 1,
                            MobileNum = "2345678901",
                            Password = "travel123",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Address = "789 Manager Street",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(373),
                            DepartmentId = 1,
                            Email = "manager@traveldesk.com",
                            FirstName = "Manager",
                            IsActive = true,
                            LastName = "User",
                            ManagerId = 1,
                            MobileNum = "3456789012",
                            Password = "manager123",
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            Address = "321 Employee Street",
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 8, 7, 16, 29, 1, 497, DateTimeKind.Utc).AddTicks(379),
                            DepartmentId = 1,
                            Email = "employee@traveldesk.com",
                            FirstName = "Employee",
                            IsActive = true,
                            LastName = "User",
                            ManagerId = 3,
                            MobileNum = "4567890123",
                            Password = "employee123",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("TravelDesk.Models.TravelRequest", b =>
                {
                    b.HasOne("TravelDesk.Models.Department", "Department")
                        .WithMany("TravelRequests")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelDesk.Models.Project", "Project")
                        .WithMany("TravelRequests")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "UserName")
                        .WithMany("TravelRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Project");

                    b.Navigation("UserName");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("TravelDesk.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TravelDesk.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TravelDesk.Models.Department", b =>
                {
                    b.Navigation("TravelRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TravelDesk.Models.Project", b =>
                {
                    b.Navigation("TravelRequests");
                });

            modelBuilder.Entity("TravelDesk.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("TravelRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
