CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE TABLE "Departments" (
        "DepartmentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "DepartmentName" character varying(50) NOT NULL,
        "CreatedBy" integer NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "ModifiedBy" text,
        "ModifiedOn" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Departments" PRIMARY KEY ("DepartmentId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE TABLE "Projects" (
        "ProjectId" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProjectName" character varying(50) NOT NULL,
        "CreatedBy" integer NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "ModifiedBy" text,
        "ModifiedOn" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Projects" PRIMARY KEY ("ProjectId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleName" character varying(50) NOT NULL,
        "CreatedBy" integer NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "ModifiedBy" text,
        "ModifiedOn" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE TABLE "Users" (
        "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(50) NOT NULL,
        "LastName" character varying(50),
        "Address" character varying(100) NOT NULL,
        "Email" text NOT NULL,
        "MobileNum" text NOT NULL,
        "Password" character varying(100) NOT NULL,
        "RoleId" integer NOT NULL,
        "DepartmentId" integer NOT NULL,
        "ManagerId" integer,
        "CreatedBy" integer NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "ModifiedBy" text,
        "ModifiedOn" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_Users_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("DepartmentId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Users_Users_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE TABLE "TravelRequests" (
        "TravelRequestId" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "ProjectId" integer NOT NULL,
        "DepartmentId" integer NOT NULL,
        "ReasonForTravel" text NOT NULL,
        "FromDate" timestamp with time zone NOT NULL,
        "ToDate" timestamp with time zone NOT NULL,
        "FromLocation" text NOT NULL,
        "ToLocation" text NOT NULL,
        "Comments" text,
        "TicketUrl" text,
        "Status" text NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "ModifiedOn" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_TravelRequests" PRIMARY KEY ("TravelRequestId"),
        CONSTRAINT "FK_TravelRequests_Departments_DepartmentId" FOREIGN KEY ("DepartmentId") REFERENCES "Departments" ("DepartmentId") ON DELETE CASCADE,
        CONSTRAINT "FK_TravelRequests_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("ProjectId") ON DELETE RESTRICT,
        CONSTRAINT "FK_TravelRequests_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    INSERT INTO "Departments" ("DepartmentId", "CreatedBy", "CreatedOn", "DepartmentName", "IsActive", "ModifiedBy", "ModifiedOn")
    VALUES (1, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715959Z', 'IT', TRUE, NULL, NULL);
    INSERT INTO "Departments" ("DepartmentId", "CreatedBy", "CreatedOn", "DepartmentName", "IsActive", "ModifiedBy", "ModifiedOn")
    VALUES (2, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715959Z', 'HR', TRUE, NULL, NULL);
    INSERT INTO "Departments" ("DepartmentId", "CreatedBy", "CreatedOn", "DepartmentName", "IsActive", "ModifiedBy", "ModifiedOn")
    VALUES (3, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715959Z', 'Admin', TRUE, NULL, NULL);
    INSERT INTO "Departments" ("DepartmentId", "CreatedBy", "CreatedOn", "DepartmentName", "IsActive", "ModifiedBy", "ModifiedOn")
    VALUES (4, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715959Z', 'Travel', TRUE, NULL, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    INSERT INTO "Projects" ("ProjectId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "ProjectName")
    VALUES (1, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715966Z', TRUE, NULL, NULL, 'Project Alpha');
    INSERT INTO "Projects" ("ProjectId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "ProjectName")
    VALUES (2, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715967Z', TRUE, NULL, NULL, 'Project Beta');
    INSERT INTO "Projects" ("ProjectId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "ProjectName")
    VALUES (3, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715967Z', TRUE, NULL, NULL, 'Project Gamma');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    INSERT INTO "Roles" ("RoleId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "RoleName")
    VALUES (1, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715941Z', TRUE, NULL, NULL, 'Admin');
    INSERT INTO "Roles" ("RoleId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "RoleName")
    VALUES (2, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715941Z', TRUE, NULL, NULL, 'TravelAdmin');
    INSERT INTO "Roles" ("RoleId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "RoleName")
    VALUES (3, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715941Z', TRUE, NULL, NULL, 'Manager');
    INSERT INTO "Roles" ("RoleId", "CreatedBy", "CreatedOn", "IsActive", "ModifiedBy", "ModifiedOn", "RoleName")
    VALUES (4, 1, TIMESTAMPTZ '2025-08-06T14:03:13.715941Z', TRUE, NULL, NULL, 'Employee');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    INSERT INTO "Users" ("UserId", "Address", "CreatedBy", "CreatedOn", "DepartmentId", "Email", "FirstName", "IsActive", "LastName", "ManagerId", "MobileNum", "ModifiedBy", "ModifiedOn", "Password", "RoleId")
    VALUES (1, '123 Admin Street', 1, TIMESTAMPTZ '2025-08-06T14:03:13.71597Z', 3, 'admin@traveldesk.com', 'Admin', TRUE, 'User', NULL, '1234567890', NULL, NULL, 'admin123', 1);
    INSERT INTO "Users" ("UserId", "Address", "CreatedBy", "CreatedOn", "DepartmentId", "Email", "FirstName", "IsActive", "LastName", "ManagerId", "MobileNum", "ModifiedBy", "ModifiedOn", "Password", "RoleId")
    VALUES (2, '456 Travel Street', 1, TIMESTAMPTZ '2025-08-06T14:03:13.71597Z', 4, 'traveladmin@traveldesk.com', 'Travel', TRUE, 'Admin', 1, '2345678901', NULL, NULL, 'travel123', 2);
    INSERT INTO "Users" ("UserId", "Address", "CreatedBy", "CreatedOn", "DepartmentId", "Email", "FirstName", "IsActive", "LastName", "ManagerId", "MobileNum", "ModifiedBy", "ModifiedOn", "Password", "RoleId")
    VALUES (3, '789 Manager Street', 1, TIMESTAMPTZ '2025-08-06T14:03:13.71597Z', 1, 'manager@traveldesk.com', 'Manager', TRUE, 'User', 1, '3456789012', NULL, NULL, 'manager123', 3);
    INSERT INTO "Users" ("UserId", "Address", "CreatedBy", "CreatedOn", "DepartmentId", "Email", "FirstName", "IsActive", "LastName", "ManagerId", "MobileNum", "ModifiedBy", "ModifiedOn", "Password", "RoleId")
    VALUES (4, '321 Employee Street', 1, TIMESTAMPTZ '2025-08-06T14:03:13.71597Z', 1, 'employee@traveldesk.com', 'Employee', TRUE, 'User', 3, '4567890123', NULL, NULL, 'employee123', 4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE INDEX "IX_TravelRequests_DepartmentId" ON "TravelRequests" ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE INDEX "IX_TravelRequests_ProjectId" ON "TravelRequests" ("ProjectId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE INDEX "IX_TravelRequests_UserId" ON "TravelRequests" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE INDEX "IX_Users_DepartmentId" ON "Users" ("DepartmentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE INDEX "IX_Users_ManagerId" ON "Users" ("ManagerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Departments"', 'DepartmentId'),
        GREATEST(
            (SELECT MAX("DepartmentId") FROM "Departments") + 1,
            nextval(pg_get_serial_sequence('"Departments"', 'DepartmentId'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Projects"', 'ProjectId'),
        GREATEST(
            (SELECT MAX("ProjectId") FROM "Projects") + 1,
            nextval(pg_get_serial_sequence('"Projects"', 'ProjectId'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Roles"', 'RoleId'),
        GREATEST(
            (SELECT MAX("RoleId") FROM "Roles") + 1,
            nextval(pg_get_serial_sequence('"Roles"', 'RoleId'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'UserId'),
        GREATEST(
            (SELECT MAX("UserId") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'UserId'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250806083314_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250806083314_InitialCreate', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Departments" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "DepartmentId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Departments" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "DepartmentId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Departments" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "DepartmentId" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Departments" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "DepartmentId" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Projects" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "ProjectId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Projects" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "ProjectId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Projects" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "ProjectId" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Roles" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.496Z'
    WHERE "RoleId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Roles" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.496Z'
    WHERE "RoleId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Roles" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.496Z'
    WHERE "RoleId" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Roles" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.496Z'
    WHERE "RoleId" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Users" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "UserId" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Users" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "UserId" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Users" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "UserId" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    UPDATE "Users" SET "CreatedOn" = TIMESTAMPTZ '2025-08-07T16:29:01.497Z'
    WHERE "UserId" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250807105902_FullSchema') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250807105902_FullSchema', '8.0.8');
    END IF;
END $EF$;
COMMIT;

